### ISSUE TITLE
SetVariable

### ISSUE THREAD

**Issue by andatt** [dsoprea/TightOCR#1]
I was just wondering if it's currently possible to use the SetVariable function within the Tesseract API via tight ocr? I can't find it anywhere in the TightOCR code but I might be missing it. I am hoping to use the whitelist/blacklist for certain characters if that helps.

Thanks

**Comment by dsoprea** [comment]
If you can explain the functionality, whether this is the only call that you require, and how I would test it, I'd be happy to add it. If you grasp the structure of the library and have the time, you can feel free to add it yourself, as well.

The only reason that TightOCR doesn't implement some of Tesseract's features is simply a lack of understanding of some of its functionalities. If I can't understand it, than I won't be able to test it properly.

**Comment by andatt** [comment]
Functionality is to restrict the characters that Tesseract can return, either via a blacklist (i.e anything not on the list is returnable) or whitelist (i.e only items on the list are returnable). Useage in Python Tesseract is:

api.SetVariable("tessedit_char_whitelist", "0123456789abcdefghijklmnopqrstuvwxyz")

This is the only call that I require, testing would involve say setting whitelist to numbers only and tesseract should only return numbers from text ocr'd.

**Comment by dsoprea** [comment]
That's cool. Yeah, no problem. I'll look at it tonight.

**Comment by dsoprea** [comment]
It's been added and tested:

CTesseract: https://github.com/dsoprea/CTesseract/commit/7ebe78dd85bf162d176b8f48ac84117f75ac71b7
TightOCR: https://github.com/dsoprea/TightOCR/commit/c23b4235d922c1f487244ad53d45f0ff9a5d088c

Update your package, and you should see it:

``` python
t = TessApi(None, 'eng');
t.set_variable('tessedit_char_whitelist', '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ\'".,;?!/\\$-()&%@')
```

**Comment by andatt** [comment]
Thanks very much for this! I re-installed both CTesseract and TightOCR but  am getting an error message when I run (even if I remove the set_variable line in the code):

Traceback (most recent call last):
  File "ctesstest.py", line 3, in <module>
    from tightocr.adapters.api_adapter import TessApi
  File "/usr/local/lib/python2.7/dist-packages/tightocr/adapters/api_adapter.py", line 7, in <module>
    from tightocr.calls.api_calls import *
  File "/usr/local/lib/python2.7/dist-packages/tightocr/calls/api_calls.py", line 249, in <module>
    c_tess_set_variable = libctess.tess_set_variable
  File "/usr/lib/python2.7/ctypes/**init**.py", line 378, in **getattr**
    func = self.**getitem**(name)
  File "/usr/lib/python2.7/ctypes/**init**.py", line 383, in **getitem**
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/local/lib/libctesseract.so.1.0.0: undefined symbol: tess_set_variable

I'm sure it's something obvious I'm doing wrong!

**Comment by dsoprea** [comment]
You're using a binary CTesseract that doesn't have that call yet. Make sure
that you've rebuilt. You can verify that it's there by using _readelf_ (on
a Linux system).

Dustin

**Comment by andatt** [comment]
Fixed! Was just using 'make' as per instructions but needed 'make install'. Works like a charm.

Thanks again - there is another request that I thought of - sorry I thought that would be the last one. Shall I start another thread?

**Comment by dsoprea** [comment]
That would've depended on whether you had done "make install" in the first
place. You could've been using it directly out of the build directory.

That's okay. You can tell me here.

**Comment by dsoprea** [comment]
I'm just going to close this issue. If you needed something else, feel free to open another issue.

**Comment by clintharris** [comment]
I also ran into the `undefined symbol: tess_set_variable` error.

Lesson-learned for anyone else who has the same problem: don't use the 1.0 tag of the project; instead use master or 0.3.2.
